name: swipe_plus
description: A new Flutter package project.
version: 0.0.2

environment:
  sdk: ">=2.17.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: